In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv('insurance_pre.csv')
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'charges'], dtype='object')

In [4]:
dataset=pd.get_dummies(dataset, dtype=int, drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

dataset

In [5]:
indep=dataset[['age', 'sex_male', 'bmi', 'children', 'smoker_yes']]
dep=dataset[['charges']]

In [6]:
from sklearn.model_selection import GridSearchCV
from sklearn.neural_network import MLPRegressor

param_grid = {'loss':['squared_error','poisson'],
'activation': ['identity','logistic','tanh','relu'],
'solver':['lbfgs','sgd','adam']}

grid = GridSearchCV(MLPRegressor(), param_grid, refit = True, verbose = 3,n_jobs=-1)
# fitting the model for grid search
grid.fit(indep, dep)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

C:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning:
24 fits failed out of a total of 120.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
24 fits failed with the following error:
Traceback (most recent call last):
  File "C:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\anaconda3\Lib\site-packages\sklearn\base.py", line 1365, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py", line 849, in fit
    return self._fit(X, y, sample_weight=sample_weight, incremental=False)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py", line 536, in _fit
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Solver produced non-finite parameter weights. The input data may contain large values and need to be preprocessed.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1135: UserWarning: One or more of the test scores are non-finite: [ 7.46641419e-01             nan  1.14838476e-01  7.52983623e-01
             nan -5.33442066e-02  3.42321170e-01 -6.16021457e-04
 -1.18425034e+00  8.21840700e-01             nan  8.06623714e-01
  2.10754626e-01  1.83833907e-02 -1.18209156e+00  8.17656163e-01
             nan  8.12761071e-01  7.71935595e-01 -2.09406142e+02
 -8.42598843e-04  7.62175313e-01             nan  5.56075284e-01]
  warnings.warn(
C:\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1771: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:602: ConvergenceWarning: lbfgs failed to converge after 200 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=200).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

GridSearchCV(estimator=MLPRegressor(), n_jobs=-1,
             param_grid={'activation': ['identity', 'logistic', 'tanh', 'relu'],
                         'loss': ['squared_error', 'poisson'],
                         'solver': ['lbfgs', 'sgd', 'adam']},
             verbose=3)

In [7]:
re=grid.cv_results_
print("The R_score value for best parameter {}:".format(grid.best_params_))
print("The R_score value {}:".format(grid.best_score_))

The R_score value for best parameter {'activation': 'logistic', 'loss': 'poisson', 'solver': 'lbfgs'}:
The R_score value 0.8218406999909117:

In [8]:
table=pd.DataFrame.from_dict(re)

In [9]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_activation,param_loss,param_solver,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.761103,0.306191,0.004991,0.000444,identity,squared_error,lbfgs,"{'activation': 'identity', 'loss': 'squared_er...",0.760979,0.708733,0.775584,0.731367,0.756544,0.746641,0.023714,8
1,1.128088,0.069802,0.000000,0.000000,identity,squared_error,sgd,"{'activation': 'identity', 'loss': 'squared_er...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,20
2,1.098954,0.025530,0.005636,0.000175,identity,squared_error,adam,"{'activation': 'identity', 'loss': 'squared_er...",0.114521,0.136806,0.112313,0.124574,0.085979,0.114838,0.016833,12
3,0.272501,0.034448,0.005446,0.000297,identity,poisson,lbfgs,"{'activation': 'identity', 'loss': 'poisson', ...",0.748845,0.716120,0.796581,0.749064,0.754308,0.752984,0.025667,7
4,0.960808,0.021851,0.000000,0.000000,identity,poisson,sgd,"{'activation': 'identity', 'loss': 'poisson', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,20
5,0.884400,0.406272,0.006887,0.003422,identity,poisson,adam,"{'activation': 'identity', 'loss': 'poisson', ...",-0.070555,-1.258036,0.653330,0.547110,-0.138570,-0.053344,0.680996,16
6,1.832558,1.775809,0.011075,0.006724,logistic,squared_error,lbfgs,"{'activation': 'logistic', 'loss': 'squared_er...",0.583680,0.489658,0.638610,-0.000179,-0.000163,0.342321,0.283673,10
7,0.382150,0.075379,0.007465,0.000301,logistic,squared_error,sgd,"{'activation': 'logistic', 'loss': 'squared_er...",-0.000039,-0.000798,-0.001811,-0.000431,-0.000001,-0.000616,0.000664,14
8,1.747033,0.022670,0.005613,0.000466,logistic,squared_error,adam,"{'activation': 'logistic', 'loss': 'squared_er...",-1.173256,-1.287242,-1.111038,-1.188709,-1.161006,-1.184250,0.057703,18
9,1.572199,0.086154,0.006488,0.000540,logistic,poisson,lbfgs,"{'activation': 'logistic', 'loss': 'poisson', ...",0.840843,0.787835,0.851107,0.804760,0.824659,0.821841,0.023125,1
10,1.917528,1.332940,0.002176,0.004352,logistic,poisson,sgd,"{'activation': 'logistic', 'loss': 'poisson', ...",NaN,NaN,NaN,NaN,-1.181544,NaN,NaN,20
11,1.789793,0.077600,0.008627,0.005111,logistic,poisson,adam,"{'activation': 'logistic', 'loss': 'poisson', ...",0.826932,0.774230,0.838454,0.793088,0.800414,0.806624,0.023224,4
12,2.020767,0.261100,0.015789,0.010861,tanh,squared_error,lbfgs,"{'activation': 'tanh', 'loss': 'squared_error'...",0.167611,0.272079,0.197510,0.239562,0.177011,0.210755,0.039410,11
13,0.342596,0.143924,0.007024,0.000700,tanh,squared_error,sgd,"{'activation': 'tanh', 'loss': 'squared_error'...",0.059369,0.036275,-0.003568,-0.000122,-0.000037,0.018383,0.025154,13
14,2.533578,0.186379,0.006355,0.000533,tanh,squared_error,adam,"{'activation': 'tanh', 'loss': 'squared_error'...",-1.171599,-1.285196,-1.108516,-1.186526,-1.158621,-1.182092,0.057835,17
15,2.317623,0.143810,0.006778,0.000294,tanh,poisson,lbfgs,"{'activation': 'tanh', 'loss': 'poisson', 'sol...",0.839251,0.760105,0.861107,0.815705,0.812112,0.817656,0.033767,2
16,1.342776,0.073138,0.000000,0.000000,tanh,poisson,sgd,"{'activation': 'tanh', 'loss': 'poisson', 'sol...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,20
17,2.134883,0.466796,0.008164,0.000699,tanh,poisson,adam,"{'activation': 'tanh', 'loss': 'poisson', 'sol...",0.851090,0.772297,0.823167,0.792554,0.824696,0.812761,0.027443,3
18,0.970062,0.285037,0.007091,0.000798,relu,squared_error,lbfgs,"{'activation': 'relu', 'loss': 'squared_error'...",0.785946,0.731844,0.775588,0.807847,0.758452,0.771936,0.025645,5
19,0.115964,0.026863,0.006723,0.000360,relu,squared_error,sgd,"{'activation': 'relu', 'loss': 'squared_error'...",-99.220444,-499.876740,-125.945401,-72.203184,-249.784939,-209.406142,157.438782,19
20,1.650544,0.061640,0.007121,0.001917,relu,squared_error,adam,"{'activation': 'relu', 'loss': 'squared_error'...",-0.063519,0.064810,0.071315,-0.050087,-0.026732,-0.000843,0.057516,15
21,1.199529,0.047510,0.006476,0.000315,relu,poisson,lbfgs,"{'activation': 'relu', 'loss': 'poisson', 'sol...",0.770250,0.719220,0.806427,0.762380,0.752599,0.762175,0.028144,6
22,1.466119,0.031675,0.000000,0.000000,relu,poisson,sgd,"{'activation': 'relu', 'loss': 'poisson', 'sol...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,20
23,1.478202,0.125116,0.005326,0.000950,relu,poisson,adam,"{'activation': 'relu', 'loss': 'poisson', 'sol...",0.682958,0.450427,0.431512,0.453703,0.761777,0.556075,0.138253,9

In [10]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 35
BMI: 42
Children: 2
Sex Male 0 or 1: 0
Smoker Yes 0 or 1: 1

In [11]:
Future_Prediction=grid.predict([[age_input,sex_male_input,bmi_input,children_input,smoker_yes_input]])
#change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[48067.40635907]

C:\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but MLPRegressor was fitted with feature names
  warnings.warn(